"""Supabase table and column names — align with your Lovable / Postgres migration."""

PERSONS_TABLE = "persons"
MATRIMONY_PROFILES_TABLE = "matrimony_profiles"
VERIFICATION_REQUESTS_TABLE = "verification_requests"
UNIONS_TABLE = "unions"
USERS_TABLE = "users"
VERIFICATION_AUDIT_TABLE = "verification_audit"
NOTIFICATIONS_TABLE = "notifications"
SALES_SETTINGS_TABLE = "sales_settings"
SALES_PERFORMANCE_TABLE = "sales_performance"
PLATFORM_CONFIG_TABLE = "platform_config"
PRICING_CONFIG_ID = "pricing"
SE_APPLICATIONS_TABLE = "se_applications"
CALENDAR_EVENTS_TABLE = "calendar_events"
LEGACY_MESSAGES_TABLE = "legacy_messages"
MEMBER_LOCATIONS_TABLE = "member_locations"
# Samay Bank v2 (replaces time_bank_offers / time_bank_transactions)
SAMAY_BRANCHES_TABLE        = "samay_branches"
SAMAY_BRANCH_MEMBERS_TABLE  = "samay_branch_members"
SAMAY_REQUESTS_TABLE        = "samay_requests"
SAMAY_TRANSACTIONS_TABLE    = "samay_transactions"
SAMAY_RATINGS_TABLE         = "samay_ratings"
SAMAY_PROFILES_TABLE        = "samay_profiles"

VANSHA_ID_COLUMN = "vansha_id"
PARENT_UNION_ID_COLUMN = "parent_union_id"
