-- Migration 020: Eco-Panchang — tithis reference table + rolling panchang_calendar
-- Run in Supabase SQL editor after migrations 001-017.

-- ── Tithis: 30 lunar days ────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.tithis (
    id                      smallint    PRIMARY KEY,  -- 1-15 Shukla, 16-30 Krishna
    paksha                  text        NOT NULL CHECK (paksha IN ('shukla','krishna')),
    tithi_number            smallint    NOT NULL,     -- 1-15 within paksha
    name_sanskrit           text        NOT NULL,
    name_hindi              text        NOT NULL,
    name_common             text        NOT NULL,

    -- Ecological significance
    eco_significance        text        NOT NULL,
    plant_action            text,
    water_action            text,
    avoid_action            text,
    nature_observation      text,

    -- Social / Sewa mapping
    sewa_category           text        NOT NULL
        CHECK (sewa_category IN (
            'tree_planting','waste_segregation','clean_up_drive',
            'water_conservation','eco_awareness','solar_adoption','composting'
        )),
    community_action        text        NOT NULL,
    ceremony_type_hint      text
        CHECK (ceremony_type_hint IN (
            'vriksha_pratishtha','jal_puja','eco_pledge',
            'dharti_sandesh','harit_circle_monthly',NULL
        )),

    -- Content templates (placeholders: {family_name} {location} {tithi_name} {date})
    blog_title_template     text        NOT NULL,
    blog_subtitle_template  text        NOT NULL,
    blog_body_template      text        NOT NULL,
    ig_caption_template     text        NOT NULL,
    ig_hashtag_set          text[]      NOT NULL DEFAULT '{}',
    yt_short_title_template text        NOT NULL,
    yt_short_desc_template  text        NOT NULL,

    created_at              timestamptz DEFAULT now()
);

-- ── Seed 30 tithis ───────────────────────────────────────────────────────────

INSERT INTO public.tithis
(id,paksha,tithi_number,name_sanskrit,name_hindi,name_common,
 eco_significance,plant_action,water_action,avoid_action,nature_observation,
 sewa_category,community_action,ceremony_type_hint,
 blog_title_template,blog_subtitle_template,blog_body_template,
 ig_caption_template,ig_hashtag_set,yt_short_title_template,yt_short_desc_template)
VALUES

-- ─── SHUKLA PAKSHA ──────────────────────────────────────────────────────────

(1,'shukla',1,'प्रतिपदा','प्रतिपदा','Pratipada',
 'Waxing moon energises new growth; strongest day for planting saplings and sowing seeds.',
 'Plant fruit trees or sow seeds — root energy peaks at sunrise.',
 'Deep water established trees before 9 AM.',
 'Avoid uprooting or transplanting established plants.',
 'Observe the first sliver of the moon rising just after sunset.',
 'tree_planting','Organise a community sapling distribution drive in your neighbourhood.','vriksha_pratishtha',
 '{family_name} का प्रतिपदा पर हरित संकल्प','{date} — नई शुरुआत, हरित भविष्य',
 'Pratipada marks the beginning of the Shukla Paksha — the waxing fortnight. For **{family_name}** in {location}, this is the most auspicious day to plant a sapling and take a green pledge for the coming month.\n\n**What the moon tells us:** As the moon begins its growth phase, sap rises more strongly in plants, making root establishment easier. Our ancestors knew this — they scheduled all major plantings around Pratipada.\n\n**Your Eco-Sewa today:** {plant_action}\n\n**Community call:** {community_action}',
 '🌱 आज प्रतिपदा है — नई शुरुआत का दिन!\n\n{community_action}\n\nअपने हरित संकल्प की शुरुआत आज से करें। 🙏',
 ARRAY['#EcoPanchang','#HaritVanshavali','#PrakritiBharat','#TreePlanting','#Pratipada','#LunarCalendar'],
 'Pratipada: Best Day to Plant Trees — Here''s Why',
 'The first lunar day is scientifically linked to stronger root growth. Learn why {family_name} plants on Pratipada.'),

(2,'shukla',2,'द्वितीया','दूज','Dwitiya',
 'Moon energy builds steadily; good day for nurturing recently planted saplings and composting.',
 'Water new saplings gently; add organic compost around roots.',
 'Check soil moisture; water slowly at root zone.',
 'Avoid heavy pruning or cutting of live branches.',
 'Notice how new buds are opening since yesterday.',
 'composting','Set up a community composting pit or vermicompost unit.','eco_pledge',
 '{family_name} की दूज पर हरित सेवा','{date} — पोषण और देखभाल का दिन',
 'Dwitiya is the second day of the Shukla Paksha — a day of nurturing. For **{family_name}** in {location}, today is ideal for composting and soil enrichment.\n\n**Eco-action:** {plant_action}\n\n**Community call:** {community_action}',
 '♻️ आज दूज है — मिट्टी को पोषण देने का दिन!\n\n{community_action}\n\nहरित सेवा करें, प्रकृति को लौटाएं। 🌿',
 ARRAY['#EcoPanchang','#Composting','#HaritVanshavali','#Dwitiya','#GreenIndia'],
 'Dwitiya: Why Today Is Perfect for Composting',
 'Learn how {family_name} uses Dwitiya to enrich their soil and build their Green Legacy.'),

(3,'shukla',3,'तृतीया','तीज','Tritiya',
 'Auspicious for water-related eco-actions; Haritalika Teej connection honours nature.',
 'Plant water-loving species: lotus, water hyacinth, wetland grasses.',
 'Clean and refill animal water troughs; check local ponds for algae.',
 'Avoid using chemical fertilisers near water bodies today.',
 'Observe waterbirds and insects near local water sources.',
 'water_conservation','Organise a local pond or riverbank clean-up drive.','jal_puja',
 '{family_name} की तीज पर जल-संरक्षण','{date} — जल है जीवन, आज जल सेवा करें',
 'Tritiya — especially Haritalika Teej — has honoured Goddess Parvati and the sacred bond between women and nature for centuries. For **{family_name}** in {location}, today is the perfect day for water conservation.\n\n**Eco-action:** {water_action}\n\n**Community call:** {community_action}',
 '💧 तीज है आज — जल सेवा का पर्व!\n\n{community_action}\n\nजल संरक्षण = जीवन संरक्षण। #JalSeva 🙏',
 ARRAY['#EcoPanchang','#WaterConservation','#Teej','#JalPuja','#HaritVanshavali'],
 'Tritiya / Teej: The Ancient Water Conservation Festival',
 'How {family_name} honours the Teej tradition by protecting water bodies in {location}.'),

(4,'shukla',4,'चतुर्थी','चौथ','Chaturthi',
 'Ganesh Chaturthi connection: Lord Ganesha is Vighnaharta — remover of obstacles in eco-restoration.',
 'Plant trees near temples or community spaces; banana and tulsi are auspicious.',
 'Water tulsi and sacred plants with devotion.',
 'Avoid burning dry leaves or waste; compost instead.',
 'Watch for ants and small insects — they are Ganesha''s companions in soil health.',
 'composting','Organise an eco-friendly Ganesh visarjan awareness drive; use clay idols.','eco_pledge',
 '{family_name} की चतुर्थी पर हरित गणेश वंदना','{date} — विघ्नहर्ता के स्वागत में प्रकृति की सेवा',
 'Chaturthi honours Lord Ganesha, whose elephant form symbolises wisdom and the strength of nature. For **{family_name}** in {location}, this day calls for composting and sacred planting.\n\n**Eco-action:** {plant_action}\n\n**Community call:** {community_action}',
 '🐘 चतुर्थी पर गणेश वंदना — प्रकृति की देखभाल!\n\n{community_action}\n\nमिट्टी की मूर्ति, शुद्ध जल विसर्जन। 🌿',
 ARRAY['#EcoPanchang','#GaneshChaturthi','#EcoFriendly','#HaritVanshavali','#Composting'],
 'Chaturthi: Eco-Friendly Ganesha and Green Legacy',
 'How {family_name} celebrates Ganesha by protecting the earth in {location}.'),

(5,'shukla',5,'पञ्चमी','पंचमी','Panchami',
 'Naga Panchami connection: honour water serpents — protect local water bodies and wetlands.',
 'Plant near water bodies; water chestnut and lotus are ideal.',
 'Clean and protect local ponds, rivers, and wells from pollution.',
 'Avoid draining or diverting natural water channels.',
 'Observe frogs, fish, and water serpents — indicators of healthy water ecosystems.',
 'water_conservation','Organise a river or pond clean-up; remove plastic and debris.','jal_puja',
 '{family_name} की पंचमी पर जल-संरक्षण','{date} — नाग पंचमी: जल और जीव की रक्षा',
 'Panchami, especially Naga Panchami, reveres the Naga — the serpent deity who guards water and underground resources. For **{family_name}** in {location}, this is the day to protect water bodies.\n\n**Eco-action:** {water_action}\n\n**Community call:** {community_action}',
 '🐍 नाग पंचमी — जल और जीव की रक्षा!\n\n{community_action}\n\nसाफ़ जल = स्वस्थ प्रकृति = स्वस्थ परिवार। 💧',
 ARRAY['#EcoPanchang','#NagaPanchami','#WaterProtection','#HaritVanshavali','#JalSeva'],
 'Naga Panchami: Ancient Wisdom for Water Conservation',
 'Why {family_name} protects rivers on Panchami — connecting ancient ritual with ecology.'),

(6,'shukla',6,'षष्ठी','छठ','Shashthi',
 'Skanda Sashti: strength and victory — channel energy into community eco-drives.',
 'Plant strong native trees: peepal, neem, bargad.',
 'Water community trees and parks with fellow residents.',
 'Avoid felling trees or clearing land unnecessarily.',
 'Observe the direction of wind and clouds — weather patterns shift around this day.',
 'clean_up_drive','Organise a community park or roadside tree-planting drive.','vriksha_pratishtha',
 '{family_name} की षष्ठी पर वृक्ष-वंदना','{date} — शक्ति और समृद्धि की षष्ठी',
 'Shashthi honours Lord Skanda — the god of strength and victory. For **{family_name}** in {location}, today''s energy is best directed into community tree-planting.\n\n**Eco-action:** {plant_action}\n\n**Community call:** {community_action}',
 '🌳 षष्ठी पर वृक्ष-वंदना!\n\n{community_action}\n\nपेड़ लगाएं, विजय पाएं। 💪🌿',
 ARRAY['#EcoPanchang','#Shashthi','#TreePlanting','#HaritVanshavali','#NativeTrees'],
 'Shashthi: Planting Strong Trees on the Day of Strength',
 '{family_name}''s tradition of planting native trees on Shashthi.'),

(7,'shukla',7,'सप्तमी','सातम','Saptami',
 'Sun-energy day — Ratha Saptami honours the sun; ideal for solar awareness and renewable energy.',
 'Plant sunflowers and sun-loving herbs like tulsi, ashwagandha.',
 'Water plants at sunrise — solar energy peaks today.',
 'Avoid using plastic bags; switch to cloth bags permanently.',
 'Observe the sunrise direction; track how it shifts across seasons.',
 'solar_adoption','Organise a solar energy awareness session in your community.','eco_pledge',
 '{family_name} की सप्तमी पर सौर-ऊर्जा संकल्प','{date} — रथ सप्तमी: सूर्य की शक्ति, हरित ऊर्जा',
 'Saptami — especially Ratha Saptami — is the festival of the sun chariot. For **{family_name}** in {location}, this is the perfect day to embrace solar energy and sun-loving plants.\n\n**Eco-action:** {plant_action}\n\n**Community call:** {community_action}',
 '☀️ सप्तमी पर सौर-ऊर्जा संकल्प!\n\n{community_action}\n\nसूर्य की शक्ति = असीमित स्वच्छ ऊर्जा। 🌞',
 ARRAY['#EcoPanchang','#Saptami','#SolarEnergy','#HaritVanshavali','#RenewableEnergy'],
 'Ratha Saptami: Sun Worship and Solar Energy — The Ancient Connection',
 'How {family_name} honours the sun by adopting clean energy in {location}.'),

(8,'shukla',8,'अष्टमी','आठम','Ashtami',
 'Radha Ashtami / Krishna Ashtami: Vrindavan''s forests — protect sacred groves and urban forests.',
 'Plant trees in community spaces; kadamba, tamala are sacred to Krishna.',
 'Water sacred groves, tulsi, and banana plants.',
 'Avoid cutting sacred trees; report illegal tree felling.',
 'Listen to birdsong at dawn — biodiversity indicator for your neighbourhood.',
 'tree_planting','Identify and protect a sacred grove or urban forest in your area.','vriksha_pratishtha',
 '{family_name} की अष्टमी पर वन-संरक्षण','{date} — कृष्ण-अष्टमी: वृन्दावन की हरियाली',
 'Ashtami connects us to the forests of Vrindavan where Lord Krishna spent his childhood. For **{family_name}** in {location}, today is for protecting sacred groves.\n\n**Eco-action:** {plant_action}\n\n**Community call:** {community_action}',
 '🌲 अष्टमी पर वन-संरक्षण!\n\n{community_action}\n\nवृन्दावन की हरियाली = हमारी ज़िम्मेदारी। 🙏',
 ARRAY['#EcoPanchang','#Ashtami','#ForestProtection','#HaritVanshavali','#Vrindavan'],
 'Ashtami: Protecting Sacred Forests Like Vrindavan',
 'How {family_name} connects Ashtami to forest conservation in {location}.'),

(9,'shukla',9,'नवमी','नौमी','Navami',
 'Ram Navami: Rama''s forest exile — 14 years of living in harmony with nature.',
 'Plant native species of forests in Chitrakoot and Dandakaranya regions.',
 'Protect rivers: Sarayu, Godavari are Ram''s sacred rivers.',
 'Avoid deforestation; raise awareness about forest rights.',
 'Observe monkeys, deer, and birds — Ram''s companions in the forest.',
 'tree_planting','Plant and protect a native tree in honour of Ram''s forest journey.','vriksha_pratishtha',
 '{family_name} की नवमी पर वन-सेवा','{date} — राम-नवमी: वनवास से वन-रक्षा',
 'Ram Navami commemorates Lord Rama''s birth — and his 14-year forest exile taught us to live in harmony with nature. For **{family_name}** in {location}, today is for planting native trees.\n\n**Eco-action:** {plant_action}\n\n**Community call:** {community_action}',
 '🌿 राम-नवमी पर वन-सेवा!\n\n{community_action}\n\nराम के वनवास से सीखें — प्रकृति के साथ जीएं। 🙏',
 ARRAY['#EcoPanchang','#RamNavami','#ForestConservation','#HaritVanshavali','#NativeTrees'],
 'Ram Navami: Lord Rama''s Forest Wisdom for Modern Conservation',
 'How {family_name} honours Ram Navami by planting trees in {location}.'),

(10,'shukla',10,'दशमी','दसमी','Dashami',
 'Vijaya Dashami energy: victory over ignorance — raise eco-awareness in your community.',
 'Plant saplings as a symbol of victory over pollution and deforestation.',
 'Water community trees; organise a tree-watering group.',
 'Avoid burning effigies with toxic materials; use natural biodegradable materials.',
 'Observe migrating birds — Dussehra season brings seasonal changes.',
 'eco_awareness','Organise an eco-awareness rally or exhibition in your neighbourhood.','eco_pledge',
 '{family_name} की दशमी पर हरित-विजय','{date} — विजयदशमी: प्रदूषण पर विजय',
 'Vijaya Dashami celebrates the victory of good over evil. For **{family_name}** in {location}, today''s victory is over pollution and environmental destruction.\n\n**Eco-action:** {plant_action}\n\n**Community call:** {community_action}',
 '🏆 विजयदशमी पर हरित-विजय!\n\n{community_action}\n\nप्रदूषण पर विजय = सच्ची दशहरे की जीत। 🌿',
 ARRAY['#EcoPanchang','#Dashami','#EcoAwareness','#HaritVanshavali','#GreenVictory'],
 'Vijaya Dashami: Victory Over Pollution — Your Family''s Green Legacy',
 'How {family_name} celebrates Dussehra by fighting environmental destruction.'),

(11,'shukla',11,'एकादशी','ग्यारस','Ekadashi',
 'Ekadashi fast day: reduce consumption, minimise waste, conserve resources.',
 'Fast from resource consumption: no new plastic purchases, reduce electricity use.',
 'Observe water sources; make a pledge to reduce water waste.',
 'Avoid wasting food; compost leftovers; donate surplus food.',
 'Notice the near-full moon rising in the east at sunset.',
 'waste_segregation','Organise a waste segregation awareness drive; separate dry and wet waste.','eco_pledge',
 '{family_name} की एकादशी पर संयम-संकल्प','{date} — एकादशी: कम उपभोग, स्वस्थ पृथ्वी',
 'Ekadashi is the fasting day — a day of restraint and mindfulness. For **{family_name}** in {location}, this is the day to reduce consumption and segregate waste.\n\n**Eco-action:** Fast from single-use plastic today. Compost food waste.\n\n**Community call:** {community_action}',
 '🙏 एकादशी पर संयम-संकल्प!\n\n{community_action}\n\nकम उपभोग = कम प्रदूषण = स्वस्थ पृथ्वी। 🌍',
 ARRAY['#EcoPanchang','#Ekadashi','#ZeroWaste','#HaritVanshavali','#SustainableLiving'],
 'Ekadashi: The Ancient Fasting Day as a Climate Action',
 'How {family_name}''s Ekadashi fast aligns with sustainability in {location}.'),

(12,'shukla',12,'द्वादशी','बारस','Dwadashi',
 'Break the fast mindfully: eat local, seasonal, and plant-based food today.',
 'Plant tulsi — sacred and medicinal; strengthens local biodiversity.',
 'Water plants slowly and deeply; check soil health after the fast.',
 'Avoid processed or packaged foods; support local farmers.',
 'Observe the near-full moon — it affects soil moisture and plant growth.',
 'water_conservation','Support a local farmer; buy seasonal produce directly.','jal_puja',
 '{family_name} की द्वादशी पर अन्न-सेवा','{date} — द्वादशी: स्थानीय अन्न, स्वस्थ धरती',
 'Dwadashi — the day after Ekadashi fast — is for mindful eating. For **{family_name}** in {location}, choose local, seasonal, and plant-based food today.\n\n**Eco-action:** {plant_action}\n\n**Community call:** {community_action}',
 '🌾 द्वादशी पर अन्न-सेवा!\n\n{community_action}\n\nस्थानीय अन्न = स्वस्थ किसान = स्वस्थ पृथ्वी। 🙏',
 ARRAY['#EcoPanchang','#Dwadashi','#LocalFood','#HaritVanshavali','#FarmToTable'],
 'Dwadashi: Breaking the Ekadashi Fast with Local Food',
 'How {family_name} connects mindful eating on Dwadashi to sustainable farming.'),

(13,'shukla',13,'त्रयोदशी','तेरस','Trayodashi',
 'Pradosh day: twilight ritual — plant trees at dusk; observe the ecology of evening hours.',
 'Plant shade trees that provide evening shelter: peepal, bargad.',
 'Water plants during the golden hour before sunset.',
 'Avoid bright artificial lighting in gardens — protect nocturnal pollinators.',
 'Watch for bats and owls emerging at dusk — they are nature''s pest controllers.',
 'tree_planting','Plant a shade tree in a community space; offer it to the neighbourhood.','vriksha_pratishtha',
 '{family_name} की त्रयोदशी पर वृक्ष-दान','{date} — प्रदोष: सांझ में वृक्ष-वंदना',
 'Trayodashi — Pradosh Vrat — is the twilight ritual of Lord Shiva. For **{family_name}** in {location}, today''s dusk is perfect for planting shade trees.\n\n**Eco-action:** {plant_action}\n\n**Community call:** {community_action}',
 '🌅 प्रदोष पर वृक्ष-दान!\n\n{community_action}\n\nसांझ में लगाया पेड़ = सुबह की ठंडी छाँव। 🌳',
 ARRAY['#EcoPanchang','#Trayodashi','#Pradosh','#HaritVanshavali','#ShadeTree'],
 'Pradosh / Trayodashi: Planting Shade Trees at Dusk',
 'How {family_name} honours Pradosh by gifting shade trees to the community.'),

(14,'shukla',14,'चतुर्दशी','चौदस','Chaturdashi',
 'Shiva Chaturdashi: strength and purification — clean water sources; avoid all pollution.',
 'Plant sacred plants: bilva (bel), rudraksha, dhatura (near Shiva temples).',
 'Purify a local water body: remove plastic and debris from ponds or streams.',
 'Avoid using chemical pesticides; use neem-based organic alternatives.',
 'Observe the near-full moon at its brightest before Purnima.',
 'water_conservation','Organise a water body purification drive near a Shiva temple or river.','jal_puja',
 '{family_name} की चतुर्दशी पर जल-शुद्धि','{date} — शिव-चतुर्दशी: जल की रक्षा, जल की पूजा',
 'Chaturdashi — especially Maha Shivratri — honours Lord Shiva, who holds the Ganga in his matted locks. For **{family_name}** in {location}, today is for purifying water bodies.\n\n**Eco-action:** {plant_action}\n\n**Community call:** {community_action}',
 '🕉️ शिव-चतुर्दशी पर जल-शुद्धि!\n\n{community_action}\n\nगंगा माँ की रक्षा = शिव की आराधना। 💧',
 ARRAY['#EcoPanchang','#Chaturdashi','#Shivratri','#HaritVanshavali','#WaterPurification'],
 'Shiva Chaturdashi: Protecting the Ganga — Ancient Ritual, Modern Action',
 'How {family_name} honours Shiva by protecting water bodies on Chaturdashi.'),

(15,'shukla',15,'पूर्णिमा','पूनम','Purnima',
 'Full moon — maximum bio-energy; strongest day for planting medicinal herbs and deep-watering.',
 'Plant medicinal herbs: ashwagandha, brahmi, shatavari, neem. Full moon amplifies growth.',
 'Deep water all trees; add organic fertiliser. Moon pulls soil moisture upward.',
 'Avoid cutting trees or harvesting roots on this powerful day.',
 'Observe the full moon reflection in water — nature at its most luminous.',
 'tree_planting','Organise a full-moon planting ceremony; plant a tree for every family member.','vriksha_pratishtha',
 '{family_name} की पूर्णिमा पर हरित-यज्ञ','{date} — पूर्णिमा: सबसे शुभ वृक्षारोपण का दिन',
 'Purnima — the full moon — is the single most powerful day in the lunar calendar for planting and eco-action. For **{family_name}** in {location}, this is the day for a family tree-planting ceremony.\n\n**Eco-action:** Plant a tree for every living family member. Deep water all existing trees.\n\n**Community call:** {community_action}',
 '🌕 पूर्णिमा पर हरित-यज्ञ!\n\n{community_action}\n\nपूर्णचंद्र की शक्ति में लगाया पेड़ = पीढ़ियों की छाँव। 🌳✨',
 ARRAY['#EcoPanchang','#Purnima','#FullMoon','#HaritVanshavali','#TreePlanting','#GreenYagna'],
 'Purnima: Why Full Moon Is the Best Day to Plant Trees',
 '{family_name}''s full moon planting ceremony — building a Green Legacy across generations.'),

-- ─── KRISHNA PAKSHA ─────────────────────────────────────────────────────────

(16,'krishna',1,'प्रतिपदा','परेवा','Krishna Pratipada',
 'Waning moon begins: good day to harvest sustainably; compost waste from the full month.',
 'Harvest ripe fruits or medicinal bark — waning moon reduces regrowth shock.',
 'Conserve water; fix leaking taps and pipes today.',
 'Avoid starting new plantings on this transition day.',
 'Notice how the moonrise shifts to later in the night.',
 'composting','Start or refresh a community composting unit; add kitchen waste.','eco_pledge',
 '{family_name} की कृष्ण-प्रतिपदा पर पुनर्चक्रण','{date} — ह्रास पक्ष: संग्रह नहीं, पुनर्चक्रण',
 'Krishna Pratipada begins the waning fortnight — a time of sustainable harvest and recycling. For **{family_name}** in {location}, today is for composting and resource conservation.\n\n**Eco-action:** {plant_action}\n\n**Community call:** {community_action}',
 '♻️ कृष्ण-प्रतिपदा पर पुनर्चक्रण!\n\n{community_action}\n\nकम लो, लौटाओ — प्रकृति का नियम। 🌿',
 ARRAY['#EcoPanchang','#KrishnaPratipada','#Recycling','#HaritVanshavali','#Composting'],
 'Krishna Pratipada: Sustainable Harvest in the Waning Moon',
 'How {family_name} uses the waning moon for composting and resource recycling.'),

(17,'krishna',2,'द्वितीया','दूज','Krishna Dwitiya',
 'Good day for soil restoration and waste segregation; moon energy supports decomposition.',
 'Add organic matter to soil; turn compost piles.',
 'Check water storage tanks; clean and conserve.',
 'Avoid burning agricultural waste; compost or mulch instead.',
 'Observe earthworms and fungi — soil health indicators.',
 'waste_segregation','Conduct a waste segregation drive; separate organic, plastic, and paper.','eco_pledge',
 '{family_name} की कृष्ण-द्वितीया पर मृदा-सेवा','{date} — मिट्टी की देखभाल = धरती की देखभाल',
 'Krishna Dwitiya supports soil restoration. For **{family_name}** in {location}, today is for improving soil health through waste segregation and composting.\n\n**Eco-action:** {plant_action}\n\n**Community call:** {community_action}',
 '🌍 कृष्ण-दूज पर मृदा-सेवा!\n\n{community_action}\n\nस्वस्थ मिट्टी = स्वस्थ अन्न = स्वस्थ परिवार। 🪱',
 ARRAY['#EcoPanchang','#SoilHealth','#WasteSegrigation','#HaritVanshavali','#Composting'],
 'Krishna Dwitiya: Healing the Soil for Future Generations',
 'How {family_name} uses the waning moon to restore soil health in {location}.'),

(18,'krishna',3,'तृतीया','तीज','Krishna Tritiya',
 'Water conservation focus continues; protect natural springs and groundwater.',
 'Plant deep-rooted trees that recharge groundwater: bargad, peepal.',
 'Observe and protect local springs, stepwells, or bore wells from contamination.',
 'Avoid drilling borewells without groundwater assessment.',
 'Notice whether local springs are flowing or shrinking.',
 'water_conservation','Map and protect all natural water sources in your village or ward.','jal_puja',
 '{family_name} की कृष्ण-तृतीया पर भूजल-संरक्षण','{date} — भूजल बचाओ, भविष्य बचाओ',
 'Krishna Tritiya calls for protecting groundwater. For **{family_name}** in {location}, today is to plant deep-rooted trees and protect natural springs.\n\n**Eco-action:** {water_action}\n\n**Community call:** {community_action}',
 '💧 कृष्ण-तृतीया पर भूजल-संरक्षण!\n\n{community_action}\n\nभूजल = अदृश्य खज़ाना — अभी बचाएं। 🌳',
 ARRAY['#EcoPanchang','#Groundwater','#WaterConservation','#HaritVanshavali','#DeepRoots'],
 'Krishna Tritiya: Protecting Groundwater with Deep-Rooted Trees',
 'How {family_name} recharges groundwater by planting bargad and peepal.'),

(19,'krishna',4,'चतुर्थी','चौथ','Krishna Chaturthi',
 'Sankashti Chaturthi: obstacle removal — clear plastic waste and eco-blockages in your area.',
 'Plant banana trees — complete ecological cycle; every part is useful.',
 'Collect and properly dispose of plastic waste from water bodies.',
 'Avoid single-use plastics; carry cloth bags and steel bottles.',
 'Observe where plastic waste accumulates — map it for community action.',
 'waste_segregation','Organise a plastic waste collection drive in your neighbourhood.','eco_pledge',
 '{family_name} की संकष्टी पर प्लास्टिक-मुक्त संकल्प','{date} — गणेश की कृपा: प्लास्टिक हटाएं, बाधाएं हटाएं',
 'Sankashti Chaturthi — the Ganesha day of the Krishna Paksha — is for removing obstacles. For **{family_name}** in {location}, today''s obstacle is plastic waste.\n\n**Eco-action:** {plant_action}\n\n**Community call:** {community_action}',
 '🐘 संकष्टी पर प्लास्टिक-मुक्त संकल्प!\n\n{community_action}\n\nप्लास्टिक हटाओ, गणेश को प्रसन्न करो। ♻️',
 ARRAY['#EcoPanchang','#Sankashti','#PlasticFree','#HaritVanshavali','#WasteCollection'],
 'Sankashti Chaturthi: Removing the Obstacle of Plastic Waste',
 'How {family_name} uses Sankashti to run a plastic-free drive in {location}.'),

(20,'krishna',5,'पञ्चमी','पंचमी','Krishna Panchami',
 'Good day for eco-awareness and education; spread knowledge of sustainable practices.',
 'Teach children to plant seeds; start a school garden.',
 'Educate about water-saving techniques; demonstrate drip irrigation.',
 'Avoid burning dry leaves; demonstrate composting as an alternative.',
 'Observe children''s connection with nature — plant their curiosity today.',
 'eco_awareness','Conduct an eco-education session with children in your locality.','eco_pledge',
 '{family_name} की कृष्ण-पंचमी पर बाल-पर्यावरण शिक्षा','{date} — बच्चों को प्रकृति से जोड़ें',
 'Krishna Panchami is ideal for eco-education. For **{family_name}** in {location}, today is to teach the next generation about sustainable living.\n\n**Eco-action:** {plant_action}\n\n**Community call:** {community_action}',
 '📚 कृष्ण-पंचमी पर बच्चों को प्रकृति से जोड़ें!\n\n{community_action}\n\nआज का बच्चा = कल का प्रकृति-रक्षक। 🌱',
 ARRAY['#EcoPanchang','#EcoEducation','#Children','#HaritVanshavali','#GreenFuture'],
 'Krishna Panchami: Teaching Children to Protect Nature',
 'How {family_name} connects the next generation to ecology on Krishna Panchami.'),

(21,'krishna',6,'षष्ठी','छठ','Krishna Shashthi',
 'Chhath Puja connection: sun and water worship — protect rivers and solar energy.',
 'Plant near riverbanks; support riverbank reforestation.',
 'Observe and protect local rivers on Chhath; collect river plastic.',
 'Avoid washing vehicles in rivers; use designated areas.',
 'Watch the sunrise and sunset over water — Chhath''s sacred ritual.',
 'water_conservation','Join or organise a Chhath-inspired river clean-up.','jal_puja',
 '{family_name} की छठ पर नदी-संरक्षण','{date} — छठ: सूर्य और नदी की पूजा',
 'Chhath Puja is one of the most ecologically conscious festivals — it venerates the Sun and the river. For **{family_name}** in {location}, today is for river protection.\n\n**Eco-action:** {water_action}\n\n**Community call:** {community_action}',
 '🌅 छठ पर नदी-संरक्षण!\n\n{community_action}\n\nनदी की पूजा = नदी की रक्षा = जीवन की रक्षा। 🙏',
 ARRAY['#EcoPanchang','#Chhath','#RiverProtection','#HaritVanshavali','#SunWorship'],
 'Chhath Shashthi: Sun Worship and River Conservation',
 'How {family_name} connects Chhath Puja to protecting rivers and solar energy.'),

(22,'krishna',7,'सप्तमी','सातम','Krishna Saptami',
 'Day for sustainable agriculture; honour farmers and local food systems.',
 'Plant vegetable seeds; support organic farming.',
 'Water kitchen gardens; encourage rooftop farming.',
 'Avoid chemical pesticides; use neem spray as alternative.',
 'Visit a local farm; observe sustainable agriculture practices.',
 'eco_awareness','Organise a farm-visit or organic market in your locality.','eco_pledge',
 '{family_name} की कृष्ण-सप्तमी पर कृषि-वंदना','{date} — किसान की थाली = धरती का उपहार',
 'Krishna Saptami honours sustainable agriculture. For **{family_name}** in {location}, today is to support local farmers and grow your own food.\n\n**Eco-action:** {plant_action}\n\n**Community call:** {community_action}',
 '🌾 कृष्ण-सप्तमी पर किसान-वंदना!\n\n{community_action}\n\nस्थानीय किसान = स्वस्थ भोजन = स्वस्थ परिवार। 🌿',
 ARRAY['#EcoPanchang','#SustainableAgriculture','#LocalFarmer','#HaritVanshavali','#OrganicFood'],
 'Krishna Saptami: Honouring Farmers and Sustainable Food',
 'How {family_name} connects to sustainable agriculture on Krishna Saptami.'),

(23,'krishna',8,'अष्टमी','आठम','Krishna Ashtami',
 'Janmashtami: Lord Krishna''s birth in Mathura''s forests — protect natural habitats.',
 'Plant native trees of Braj: kadamba, ashoka, tamala.',
 'Water sacred trees; protect old-growth trees in your area.',
 'Avoid all forms of animal cruelty; provide water for animals.',
 'Observe peacocks and cuckoos — sacred to Krishna.',
 'tree_planting','Plant a kadamba or ashoka tree; it is sacred to Lord Krishna.','vriksha_pratishtha',
 '{family_name} की जन्माष्टमी पर वन-वंदना','{date} — कृष्ण-जन्माष्टमी: बृज-वन की रक्षा',
 'Janmashtami celebrates Lord Krishna''s birth in the forests of Braj. For **{family_name}** in {location}, today is for planting native trees of Braj.\n\n**Eco-action:** {plant_action}\n\n**Community call:** {community_action}',
 '🦚 जन्माष्टमी पर वन-वंदना!\n\n{community_action}\n\nकृष्ण के बृज-वन = हमारी विरासत। 🌳🙏',
 ARRAY['#EcoPanchang','#Janmashtami','#ForestProtection','#HaritVanshavali','#BrajVan'],
 'Janmashtami: Protecting the Forests of Braj',
 'How {family_name} honours Krishna by protecting native forests on Ashtami.'),

(24,'krishna',9,'नवमी','नौमी','Krishna Navami',
 'Purification day: clean up pollution; reduce your carbon footprint.',
 'Plant air-purifying indoor plants: spider plant, peace lily, money plant.',
 'Use water wisely; avoid running taps unnecessarily.',
 'Avoid burning waste; report open burning to local authorities.',
 'Check your home for energy leaks; switch to LED lighting.',
 'eco_awareness','Conduct a carbon footprint awareness session in your community.','eco_pledge',
 '{family_name} की कृष्ण-नवमी पर वायु-शुद्धि','{date} — शुद्ध वायु = स्वस्थ परिवार',
 'Krishna Navami is a day of purification. For **{family_name}** in {location}, today is to improve air quality and reduce your carbon footprint.\n\n**Eco-action:** {plant_action}\n\n**Community call:** {community_action}',
 '🌬️ कृष्ण-नवमी पर वायु-शुद्धि!\n\n{community_action}\n\nस्वच्छ वायु = स्वस्थ बच्चे = स्वस्थ भविष्य। 🌿',
 ARRAY['#EcoPanchang','#AirPurification','#CarbonFootprint','#HaritVanshavali','#CleanAir'],
 'Krishna Navami: Purifying the Air for Your Family''s Health',
 'How {family_name} uses Krishna Navami to improve air quality in {location}.'),

(25,'krishna',10,'दशमी','दसमी','Krishna Dashami',
 'Day of community service; Eco-Sewa is the highest form of social service.',
 'Plant trees in public spaces: parks, schools, roadsides.',
 'Install animal water stations; refill existing ones.',
 'Avoid noise pollution; observe quiet hours in your area.',
 'Watch for migratory birds; biodiversity in October-November increases.',
 'tree_planting','Plant 10 trees in a public space with your community today.','vriksha_pratishtha',
 '{family_name} की कृष्ण-दशमी पर दश-वृक्ष सेवा','{date} — दस पेड़, दस संकल्प',
 'Krishna Dashami is a day for community service. For **{family_name}** in {location}, today is to plant ten trees in a public space — one for each direction of service.\n\n**Eco-action:** {plant_action}\n\n**Community call:** {community_action}',
 '🌳 कृष्ण-दशमी पर दश-वृक्ष सेवा!\n\n{community_action}\n\nदस पेड़ = दस पीढ़ियों की छाँव। 💚',
 ARRAY['#EcoPanchang','#TenTrees','#CommunityService','#HaritVanshavali','#GreenLegacy'],
 'Krishna Dashami: Planting Ten Trees for Ten Generations',
 'How {family_name} builds their Green Legacy by planting ten trees on Dashami.'),

(26,'krishna',11,'एकादशी','ग्यारस','Krishna Ekadashi',
 'Nirjala Ekadashi / Vaikunta Ekadashi: strictest fast — observe complete resource conservation.',
 'No new purchases; repair and reuse instead of buying new.',
 'Observe complete water conservation; fix all leaks.',
 'Avoid all waste generation; compost, donate, or recycle everything.',
 'Observe the night sky without lights — light pollution awareness.',
 'waste_segregation','Repair café or "fix-it" workshop: repair instead of replace.','eco_pledge',
 '{family_name} की कृष्ण-एकादशी पर सम्पूर्ण संयम','{date} — पूर्ण उपवास: सम्पूर्ण संरक्षण',
 'Krishna Ekadashi — especially Nirjala Ekadashi — is the strictest fast day. For **{family_name}** in {location}, today is for complete resource conservation.\n\n**Eco-action:** Nothing new today. Repair, reuse, recycle.\n\n**Community call:** {community_action}',
 '🙏 कृष्ण-एकादशी पर सम्पूर्ण संयम!\n\n{community_action}\n\nउपवास = उपभोग से मुक्ति = पृथ्वी की मुक्ति। 🌍',
 ARRAY['#EcoPanchang','#KrishnaEkadashi','#ZeroWaste','#HaritVanshavali','#RepairCafe'],
 'Krishna Ekadashi: The Strictest Fast as a Climate Action',
 'How {family_name}''s Krishna Ekadashi fast aligns with zero-waste living.'),

(27,'krishna',12,'द्वादशी','बारस','Krishna Dwadashi',
 'Mindful return from fast; support local, organic, and plant-based food systems.',
 'Plant a kitchen garden; grow your own herbs and vegetables.',
 'Water kitchen garden; encourage friends and family to grow food.',
 'Avoid importing food from far distances today; eat local.',
 'Observe local birds feeding on garden plants — they are your garden helpers.',
 'composting','Start a kitchen garden or balcony garden in your home today.','eco_pledge',
 '{family_name} की कृष्ण-द्वादशी पर रसोई-वाटिका','{date} — अपनी मिट्टी में उगाएं, अपने हाथ से खाएं',
 'Krishna Dwadashi is for returning mindfully from the fast. For **{family_name}** in {location}, today is to plant a kitchen garden and grow your own food.\n\n**Eco-action:** {plant_action}\n\n**Community call:** {community_action}',
 '🥗 कृष्ण-द्वादशी पर रसोई-वाटिका!\n\n{community_action}\n\nअपनी मिट्टी में उगाया अन्न = सबसे पवित्र भोजन। 🌿',
 ARRAY['#EcoPanchang','#KitchenGarden','#GrowYourOwn','#HaritVanshavali','#LocalFood'],
 'Krishna Dwadashi: Growing Your Own Food — The Ancient Green Practice',
 'How {family_name} starts a kitchen garden on Krishna Dwadashi.'),

(28,'krishna',13,'त्रयोदशी','तेरस','Krishna Trayodashi',
 'Dhanteras / Pradosh: wealth and prosperity — true wealth is environmental abundance.',
 'Plant fruit trees that give returns for generations: mango, jamun, amla.',
 'Invest in water harvesting structures; rainwater collection is true wealth.',
 'Avoid buying new electronic items; repair existing ones.',
 'Notice the increasingly dark sky — new moon approaches.',
 'tree_planting','Plant a fruit tree as your family''s long-term green investment.','vriksha_pratishtha',
 '{family_name} की धनतेरस पर हरित-धन','{date} — धनतेरस: पेड़ ही असली धन',
 'Dhanteras is the festival of wealth and prosperity. For **{family_name}** in {location}, the truest wealth is a fruit tree that gives returns for generations.\n\n**Eco-action:** {plant_action}\n\n**Community call:** {community_action}',
 '🌳 धनतेरस पर हरित-धन!\n\n{community_action}\n\nफलदार पेड़ = पीढ़ियों का धन, प्रकृति का उपहार। 💰🌿',
 ARRAY['#EcoPanchang','#Dhanteras','#GreenWealth','#HaritVanshavali','#FruitTree'],
 'Dhanteras: Planting a Fruit Tree as Your Family''s True Wealth',
 'How {family_name} invests in a Green Legacy on Dhanteras.'),

(29,'krishna',14,'चतुर्दशी','चौदस','Krishna Chaturdashi',
 'Narak Chaturdashi / Kali Chaudas: overcoming darkness — choose clean energy over fossil fuels.',
 'Plant aromatic plants: camphor, tulsi, mogra — natural air purifiers.',
 'Use earthen diyas filled with ghee or mustard oil — not petroleum-based candles.',
 'Avoid crackers and fireworks; celebrate Diwali eco-consciously.',
 'Observe pre-new moon sky; maximum star visibility — nature''s light show.',
 'solar_adoption','Organise an eco-Diwali awareness drive; promote earthen diyas and LED lights.','eco_pledge',
 '{family_name} की चौदस पर हरित-दीपावली','{date} — चतुर्दशी: मिट्टी के दीये, स्वच्छ आकाश',
 'Narak Chaturdashi precedes Diwali. For **{family_name}** in {location}, today is to celebrate eco-consciously with earthen diyas and no crackers.\n\n**Eco-action:** {plant_action}\n\n**Community call:** {community_action}',
 '🪔 चतुर्दशी पर हरित-दीपावली!\n\n{community_action}\n\nमिट्टी के दीये, नीला आकाश, स्वच्छ दीवाली। 🌟',
 ARRAY['#EcoPanchang','#EcoDiwali','#EarthernDiya','#HaritVanshavali','#NoCrackers'],
 'Kali Chaudas: Eco-Diwali — Earthen Diyas and Clean Skies',
 'How {family_name} celebrates Diwali without crackers on Chaturdashi.'),

(30,'krishna',15,'अमावस्या','अमावस','Amavasya',
 'New moon — darkest night: honour ancestors by planting in their memory; pitru-tarpan with trees.',
 'Plant a tree in memory of a deceased family member — pitru-smaran vriksha.',
 'Perform tarpan near a river or water body; clean it as an offering.',
 'Avoid all forms of environmental destruction on this sacred day.',
 'Observe the new moon — the sky is at its darkest and most star-filled.',
 'tree_planting','Plant a tree in honour of an ancestor; add a nameplate as a living memorial.','dharti_sandesh',
 '{family_name} की अमावस्या पर पितृ-स्मरण वृक्ष','{date} — अमावस्या: पूर्वजों की स्मृति में वृक्षारोपण',
 'Amavasya — the new moon — is the most sacred day for remembering ancestors. For **{family_name}** in {location}, the most meaningful offering to your ancestors is planting a tree in their memory.\n\n**Eco-action:** Plant one tree for each ancestor you wish to honour. Add a nameplate.\n\n**Community call:** {community_action}\n\nThis is your living Harit Vanshavali — your green family tree.',
 '🌑 अमावस्या पर पितृ-स्मरण वृक्ष!\n\n{community_action}\n\nपूर्वजों की याद = एक पेड़, एक जीवित स्मारक। 🌳🙏',
 ARRAY['#EcoPanchang','#Amavasya','#PitruSmaran','#HaritVanshavali','#AncestralTree','#GreenLegacy'],
 'Amavasya: Planting Trees in Memory of Ancestors — A Living Legacy',
 'How {family_name} honours ancestors on Amavasya by planting memorial trees.')

ON CONFLICT (id) DO NOTHING;


-- ── Panchang Calendar: Rolling 90-day window ─────────────────────────────────

CREATE TABLE IF NOT EXISTS public.panchang_calendar (
    id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    gregorian_date  date        NOT NULL UNIQUE,
    tithi_id        smallint    NOT NULL REFERENCES public.tithis(id),
    tithi_start_ts  timestamptz,
    tithi_end_ts    timestamptz,
    is_kshaya       boolean     NOT NULL DEFAULT false,
    is_adhika       boolean     NOT NULL DEFAULT false,
    sunrise_ts      timestamptz,
    samvat_year     smallint,
    masa_name       text,
    paksha          text        NOT NULL CHECK (paksha IN ('shukla','krishna')),
    nakshatra       text,
    yoga            text,
    special_flag    text
        CHECK (special_flag IN (
            'ekadashi','purnima','amavasya','sankranti',
            'pradosh','chaturthi','navami','ashtami',NULL
        )),
    ref_lat         numeric(9,6) NOT NULL DEFAULT 23.1809,
    ref_lon         numeric(9,6) NOT NULL DEFAULT 75.7771,
    source          text        NOT NULL DEFAULT 'drik_panchanga'
        CHECK (source IN ('drik_panchanga','manual')),
    seeded_at       timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_panchang_date  ON public.panchang_calendar (gregorian_date);
CREATE INDEX IF NOT EXISTS idx_panchang_tithi ON public.panchang_calendar (tithi_id, gregorian_date);
CREATE INDEX IF NOT EXISTS idx_panchang_flag  ON public.panchang_calendar (special_flag, gregorian_date)
    WHERE special_flag IS NOT NULL;

-- Public read access — no auth needed for calendar lookups
ALTER TABLE public.tithis           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.panchang_calendar ENABLE ROW LEVEL SECURITY;

CREATE POLICY "tithis_public_read" ON public.tithis
    FOR SELECT USING (true);
CREATE POLICY "panchang_public_read" ON public.panchang_calendar
    FOR SELECT USING (true);
